name: ESLint

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    eslint:
        name: Run eslint scanning
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            # Required for private repositories by github/codeql-action/upload-sarif
            actions: read
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

            - name: Install
              run: npm ci

            - name: Lint
              run: npx eslint .
                  --format @microsoft/eslint-formatter-sarif
                  --output-file eslint-results.sarif
              continue-on-error: true

            - name: Report
              uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4
              with:
                  sarif_file: eslint-results.sarif
                  wait-for-processing: true
